=== SneazeMeat/Bibhu-Manandhar/catalog_18029955.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="BibhuUsedCars">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Details">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Logo">
								<xs:complexType>
								</xs:complexType>
							</xs:element>
							<xs:element name="Shop_Name" type="xs:string"/>
							<xs:element name="Address" type="xs:string"/>
							<xs:element name="Telephone" type="xs:string"/>
							<xs:element name="URL" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Cars">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Vehicle_Type" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Car_Type" type="xs:string"/>
										<xs:element name="Description" type="xs:string"/>
										<xs:element name="Available" type="xs:integer"/>
										<xs:element name="Brands">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Brand" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="Image">
																	<xs:complexType>
																	</xs:complexType>
																</xs:element>
																<xs:element name="BrandName" type="xs:string"/>
																<xs:element name="CarName" type="xs:string"/>
																<xs:element name="Type">
																	<xs:simpleType>
																		<xs:restriction base="xs:string">
																			<xs:enumeration value="Fuel"/>
																			<xs:enumeration value="Electric"/>
																			<xs:enumeration value="Hybrid"/>
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>
																<xs:element name="Fuel_Type" minOccurs="0">
																	<xs:simpleType>
																		<xs:restriction base="xs:string">
																			<xs:enumeration value="Petrol"/>
																			<xs:enumeration value="Diesel"/>
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>
																<xs:element name="Fuel_Capacity" type="xs:string" minOccurs="0"/>
																<xs:element name="Battery_Capacity" type="xs:string" minOccurs="0"/>
																<xs:element name="Full_Charge_Time" type="xs:string" minOccurs="0"/>
																<xs:element name="Energy_Consumption" type="xs:string" minOccurs="0"/>
																<xs:element name="Condition">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="Condition_Type" type="xs:string"/>
																			<xs:element name="Previous_Owners" type="xs:integer"/>
																			<xs:element name="Kilometers_Run" type="xs:decimal"/>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
																<xs:element name="Color" type="xs:string"/>
																<xs:element name="Price" type="xs:string"/>
																<xs:element name="Manufacture_Year" type="xs:integer"/>
																<xs:element name="Milage" type="xs:string" minOccurs="0"/>
																<xs:element name="Electric_Range" type="xs:string" minOccurs="0"/>
																<xs:element name="Transmission" type="xs:integer"/>
																<xs:element name="Vehicle_Features">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="Air_Bag" minOccurs="0">
																				<xs:simpleType>
																					<xs:restriction base="xs:string">
																						<xs:enumeration value="Yes"/>
																						<xs:enumeration value="No"/>
																					</xs:restriction>
																				</xs:simpleType>
																			</xs:element>
																			<xs:element name="ABS" minOccurs="0">
																				<xs:simpleType>
																					<xs:restriction base="xs:string">
																						<xs:enumeration value="Yes"/>
																						<xs:enumeration value="No"/>
																					</xs:restriction>
																				</xs:simpleType>
																			</xs:element>	
																			<xs:element name="Tubeless_Tyres" minOccurs="0">
																				<xs:simpleType>
																					<xs:restriction base="xs:string">
																						<xs:enumeration value="Yes"/>
																						<xs:enumeration value="No"/>
																					</xs:restriction>
																				</xs:simpleType>
																			</xs:element>
																			<xs:element name="Alloy_Wheels" minOccurs="0">
																				<xs:simpleType>
																					<xs:restriction base="xs:string">
																						<xs:enumeration value="Yes"/>
																						<xs:enumeration value="No"/>
																					</xs:restriction>
																				</xs:simpleType>
																			</xs:element>	
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
															<xs:attribute name="BID" type="xs:string"/>
															<xs:attribute name="VID">
																<xs:simpleType>
																	<xs:restriction base="xs:string">
																		<xs:enumeration value="HB"/>
																		<xs:enumeration value="SD"/>
																		<xs:enumeration value="SUV"/>
																		<xs:enumeration value="MV"/>
																	</xs:restriction>
																</xs:simpleType>
															</xs:attribute>
														</xs:complexType>
													</xs:element>	
												</xs:sequence>
											</xs:complexType>
										</xs:element>	
									</xs:sequence>
									<xs:attribute name="VID">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="HB"/>
												<xs:enumeration value="SD"/>
												<xs:enumeration value="SUV"/>
												<xs:enumeration value="MV"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>	
		</xs:complexType>		
	</xs:element>
</xs:schema>

=== SneazeMeat/Bibhu-Manandhar/Development/catalog_18029955.xml
<?xml version="1.0" encoding="utf-8"?>

<?xml-stylesheet type="text/css" href="catalog_18029955.css"?>

<BibhuUsedCars xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalog_18029955.xsd">
	<Details>
		<Logo></Logo>
		<Shop_Name>BibhuUsedCars</Shop_Name>
		<Address>Bafal, Kathmandu</Address>
		<Telephone>01-4283383</Telephone>
		<URL>www.bibhucars.com</URL>
	</Details>
	<Cars>
		<Vehicle_Type VID="HB">
			<Car_Type>Hatchback</Car_Type>
			<Description>A hatchback car is a vehicle that has a 
			large door in the back that swings upward.</Description>
			<Available>5</Available>
			<Brands>
				<Brand BID="HB-01" VID="HB">
					<Image></Image>
					<BrandName>Maruti Suzuki</BrandName>
					<CarName>Swift</CarName>
					<Type>Fuel</Type>
					<Fuel_Type>Petrol</Fuel_Type>
					<Fuel_Capacity>42 litres</Fuel_Capacity>
					<Condition>
						<Condition_Type>Used</Condition_Type>
						<Previous_Owners>2</Previous_Owners>
						<Kilometers_Run>30000</Kilometers_Run>
					</Condition>
					<Color>Solid Fire Red</Color>
					<Price>Rs 31.99 lakh</Price>
					<Manufacture_Year>2017</Manufacture_Year>
					<Milage>20 kmpl</Milage>
					<Transmission>5</Transmission>
					<Vehicle_Features>
						<Air_Bag>Yes</Air_Bag>
						<ABS>No</ABS>
						<Tubeless_Tyres>No</Tubeless_Tyres>
						<Alloy_Wheels>Yes</Alloy_Wheels>
					</Vehicle_Features>
				</Brand>	
				<Brand BID="HB-02" VID="HB">
					<Image></Image>
					<BrandName>Maruti Suzuki</BrandName>
					<CarName>Baleno</CarName>
					<Type>Fuel</Type>
					<Fuel_Type>Petrol</Fuel_Type>
					<Fuel_Capacity>37 litres</Fuel_Capacity>
					<Condition>
						<Condition_Type>Used</Condition_Type>
						<Previous_Owners>1</Previous_Owners>
						<Kilometers_Run>25000</Kilometers_Run>
					</Condition>
					<Color>Pearl Phoenix Red</Color>
					<Price>Rs 34.00 lakh</Price>
					<Manufacture_Year>2019</Manufacture_Year>
					<Milage>27 kmpl</Milage>
					<Transmission>5</Transmission>
					<Vehicle_Features>
						<Air_Bag>Yes</Air_Bag>
						<ABS>Yes</ABS>
						<Tubeless_Tyres>Yes</Tubeless_Tyres>
						<Alloy_Wheels>No</Alloy_Wheels>
					</Vehicle_Features>
				</Brand>	
				<Brand BID="HB-03" VID="HB">
					<Image></Image>
					<BrandName>Hyundai</BrandName>
					<CarName>Santro</CarName>
					<Type>Fuel</Type>
					<Fuel_Type>Petrol</Fuel_Type>
					<Fuel_Capacity>35 litres</Fuel_Capacity>
					<Condition>
						<Condition_Type>New</Condition_Type>
						<Previous_Owners>0</Previous_Owners>
						<Kilometers_Run>500</Kilometers_Run>
					</Condition>
					<Color>Light Grey</Color>
					<Price>Rs 24.96 lakh</Price>
					<Manufacture_Year>2019</Manufacture_Year>
					<Milage>20 kmpl</Milage>
					<Transmission>5</Transmission>
					<Vehicle_Features>
						<Air_Bag>Yes</Air_Bag>
						<ABS>No</ABS>
						<Tubeless_Tyres>No</Tubeless_Tyres>
						<Alloy_Wheels>No</Alloy_Wheels>
					</Vehicle_Features>
				</Brand>
				<Brand BID="HB-04" VID="HB">
					<Image></Image>
					<BrandName>Volkswagen</BrandName>
					<CarName>Polo</CarName>
					<Type>Fuel</Type>
					<Fuel_Type>Petrol</Fuel_Type>
					<Fuel_Capacity>45 litres</Fuel_Capacity>
					<Condition>
						<Condition_Type>New</Condition_Type>
						<Previous_Owners>1</Previous_Owners>
						<Kilometers_Run>45500</Kilometers_Run>
					</Condition>
					<Color>Copper Orange</Color>
					<Price>Rs 28.95 lakh</Price>
					<Manufacture_Year>2018</Manufacture_Year>
					<Milage>19 kmpl</Milage>
					<Transmission>5</Transmission>
					<Vehicle_Features>
						<Air_Bag>Yes</Air_Bag>
						<ABS>Yes</ABS>
						<Tubeless_Tyres>Yes</Tubeless_Tyres>
						<Alloy_Wheels>Yes</Alloy_Wheels>
					</Vehicle_Features>
				</Brand>
				<Brand BID="HB-05" VID="HB">
					<Image></Image>
					<BrandName>Hyundai</BrandName>
					<CarName>Ioniq</CarName>
					<Type>Electric</Type>
					<Battery_Capacity>1.56 kWh</Battery_Capacity>
					<Full_Charge_Time>4 hours 20 min</Full_Charge_Time>
					<Energy_Consumption>12.61 kWh/100km</Energy_Consumption>
					<Condition>
						<Condition_Type>New</Condition_Type>
						<Previous_Owners>1</Previous_Owners>
						<Kilometers_Run>200</Kilometers_Run>
					</Condition>
					<Color>Black Noir Pearl</Color>
					<Price>Rs 34.00 lakh</Price>
					<Manufacture_Year>2019</Manufacture_Year>
					<Electric_Range>311 km</Electric_Range>
					<Transmission>1</Transmission>
					<Vehicle_Features>
						<Air_Bag>Yes</Air_Bag>
						<ABS>Yes</ABS>
						<Tubeless_Tyres>Yes</Tubeless_Tyres>
						<Alloy_Wheels>Yes</Alloy_Wheels>
					</Vehicle_Features>
				</Brand>
			</Brands>
		</Vehicle_Type>
			
		<Vehicle_Type VID="SD">
			<Car_Type>Sedan</Car_Type>
			<Description>These are four-door vehicles which can accommodate two passengers in the front, 
			including the driver, and three in the rear seat. However, every car in the country has a similar 
			5-seater structure, but what differentiates a sedan from the rest is its trunk space which juts
			out from the rear.</Description>
			<Available>5</Available>
			<Brands>
				<Brand BID="SD-01" VID="SD">
					<Image></Image>
					<BrandName>Honda</BrandName>
					<CarName>Amaze</CarName>
					<Type>Fuel</Type>
					<Fuel_Type>Petrol</Fuel_Type>
					<Fuel_Capacity>35 litres</Fuel_Capacity>
					<Condition>
						<Condition_Type>Used</Condition_Type>
						<Previous_Owners>2</Previous_Owners>
						<Kilometers_Run>50000</Kilometers_Run>
					</Condition>
					<Color>White Orchid Pearl</Color>
					<Price>Rs 32.75 lakh</Price>
					<Manufacture_Year>2018</Manufacture_Year>
					<Milage>25 kmpl</Milage>
					<Transmission>5</Transmission>
					<Vehicle_Features>
						<Air_Bag>Yes</Air_Bag>
						<ABS>No</ABS>
						<Tubeless_Tyres>No</Tubeless_Tyres>
						<Alloy_Wheels>No</Alloy_Wheels>
					</Vehicle_Features>
				</Brand>
				<Brand BID="SD-02" VID="SD">
					<Image></Image>
					<BrandName>Honda</BrandName>
					<CarName>City</CarName>
					<Type>Fuel</Type>
					<Fuel_Type>Petrol</Fuel_Type>
					<Fuel_Capacity>40 litres</Fuel_Capacity>
					<Condition>
						<Condition_Type>Used</Condition_Type>
						<Previous_Owners>1</Previous_Owners>
						<Kilometers_Run>65000</Kilometers_Run>
					</Condition>
					<Color>Dark Grey</Color>
					<Price>Rs 43.00 lakh</Price>
					<Manufacture_Year>2017</Manufacture_Year>
					<Milage>18 kmpl</Milage>
					<Transmission>5</Transmission>
					<Vehicle_Features>
						<Air_Bag>Yes</Air_Bag>
						<ABS>Yes</ABS>
						<Tubeless_Tyres>No</Tubeless_Tyres>
						<Alloy_Wheels>Yes</Alloy_Wheels>
					</Vehicle_Features>
				</Brand>
				<Brand BID="SD-03" VID="SD">
					<Image></Image>
					<BrandName>Volkswagen</BrandName>
					<CarName>Vento</CarName>
					<Type>Fuel</Type>
					<Fuel_Type>Diesel</Fuel_Type>
					<Fuel_Capacity>55 litres</Fuel_Capacity>
					<Condition>
						<Condition_Type>Used</Condition_Type>
						<Previous_Owners>1</Previous_Owners>
						<Kilometers_Run>40000</Kilometers_Run>
					</Condition>
					<Color>Lapiz Blue</Color>
					<Price>Rs 38.95 lakh</Price>
					<Manufacture_Year>2018</Manufacture_Year>
					<Milage>16 kmpl</Milage>
					<Transmission>5</Transmission>
					<Vehicle_Features>
						<Air_Bag>No</Air_Bag>
						<ABS>Yes</ABS>
						<Tubeless_Tyres>Yes</Tubeless_Tyres>
						<Alloy_Wheels>No</Alloy_Wheels>
					</Vehicle_Features>
				</Brand>
				<Brand BID="SD-04" VID="SD">
					<Image></Image>
					<BrandName>Nissan</BrandName>
					<CarName>Sunny</CarName>
					<Type>Fuel</Type>
					<Fuel_Type>Petrol</Fuel_Type>
					<Fuel_Capacity>41 litres</Fuel_Capacity>
					<Condition>
						<Condition_Type>Used</Condition_Type>
						<Previous_Owners>3</Previous_Owners>
						<Kilometers_Run>87000</Kilometers_Run>
					</Condition>
					<Color>Onyx Black</Color>
					<Price>Rs 38.99 lakh</Price>
					<Manufacture_Year>2015</Manufacture_Year>
					<Milage>22 kmpl</Milage>
					<Transmission>5</Transmission>
					<Vehicle_Features>
						<Air_Bag>No</Air_Bag>
						<ABS>No</ABS>
						<Tubeless_Tyres>No</Tubeless_Tyres>
						<Alloy_Wheels>Yes</Alloy_Wheels>
					</Vehicle_Features>
				</Brand>
				<Brand BID="SD-05" VID="SD">
					<Image></Image>
					<BrandName>Suzuki</BrandName>
					<CarName>Dzire</CarName>
					<Type>Fuel</Type>
					<Fuel_Type>Petrol</Fuel_Type>
					<Fuel_Capacity>42 litres</Fuel_Capacity>
					<Condition>
						<Condition_Type>Used</Condition_Type>
						<Previous_Owners>1</Previous_Owners>
						<Kilometers_Run>35000</Kilometers_Run>
					</Condition>
					<Color>Azure Grey</Color>
					<Price>Rs 32.49 lakh</Price>
					<Manufacture_Year>2018</Manufacture_Year>
					<Milage>23 kmpl</Milage>
					<Transmission>5</Transmission>
					<Vehicle_Features>
						<Air_Bag>Yes</Air_Bag>
						<ABS>Yes</ABS>
						<Tubeless_Tyres>Yes</Tubeless_Tyres>
						<Alloy_Wheels>No</Alloy_Wheels>
					</Vehicle_Features>
				</Brand>
			</Brands>
		</Vehicle_Type>
		
		<Vehicle_Type VID="SUV">
			<Car_Type>SUV</Car_Type>
			<Description>Sport utility vehicle is a category of motor vehicles that combine elements
			of road-going passenger cars with features from off-road vehicles, such as raised ground 
			clearance and four-wheel drive.</Description>
			<Available>5</Available>
			<Brands>
				<Brand BID="SUV-01" VID="SUV">
					<Image></Image>
					<BrandName>Ford</BrandName>
					<CarName>Ecosport</CarName>
					<Type>Fuel</Type>
					<Fuel_Type>Diesel</Fuel_Type>
					<Fuel_Capacity>52 litres</Fuel_Capacity>
					<Condition>
						<Condition_Type>Used</Condition_Type>
						<Previous_Owners>1</Previous_Owners>
						<Kilometers_Run>33200</Kilometers_Run>
					</Condition>
					<Color>Diamond White</Color>
					<Price>Rs 47.40 lakh</Price>
